// Generated by Selenium IDE
const { Builder, By, Key, until } = require('./node_modules/selenium-webdriver')
const assert = require('assert')

describe('Employee search test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Employee search test', async function() {
    await driver.get("https://merchant-dashboard.herokuapp.com/")
    await driver.manage().window().setRect(1366, 768)
    await driver.findElement(By.id("normal_login_username")).click()
    await driver.findElement(By.id("normal_login_username")).sendKeys("merchant")
    await driver.findElement(By.id("normal_login_password")).click()
    await driver.findElement(By.id("normal_login_password")).sendKeys("nova")
    await driver.findElement(By.css(".ant-btn > span")).click()
    await driver.wait(until.elementLocated(By.id("imeKorisnika")), 30000)
    await driver.findElement(By.linkText("Employees")).click()
    await driver.findElement(By.css(".ant-table-cell:nth-child(3) .ant-table-filter-trigger")).click()
    await driver.findElement(By.css(".ant-input")).sendKeys("dselimovic1")
    await driver.findElement(By.css(".ant-input")).sendKeys(Key.ENTER)
    {
      const elements = await driver.findElements(By.linkText("Denis"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.linkText("dselimovic1@etf.unsa.ba"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.linkText("aturkusic1@etf.unsa.ba"))
      assert(!elements.length)
    }
    {
      const elements = await driver.findElements(By.linkText("Jasmin"))
      assert(!elements.length)
    }
    await driver.close()
  })
})
