// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Wrong username test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Wrong username test', async function() {
    await driver.get("https://merchant-dashboard.herokuapp.com/")
    await driver.manage().window().setRect(974, 696)
    await driver.findElement(By.id("normal_login_username")).click()
    await driver.findElement(By.id("normal_login_username")).sendKeys("merchant1")
    await driver.findElement(By.id("normal_login_password")).sendKeys("nova")
    await driver.findElement(By.css(".ant-btn > span")).click()
    await driver.wait(until.elementLocated(By.css(".ant-message-custom-content")), 30000)
    {
      const element = await driver.findElement(By.css(".ant-btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.close()
  })
})
